name: Build MCP Server

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12']
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install builder
        run: |
          curl -sSL https://raw.githubusercontent.com/capten-ai/mise-tasks-mcp/main/scripts/universal-mcp-builder.py -o builder.py
          chmod +x builder.py
      
      - name: Build standalone executable
        run: python builder.py --project . --output dist/
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mise-tasks-mcp-${{ matrix.os }}
          path: dist/
